# -*- coding: utf-8 -*-
"""lab2_2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwERW5PucJnJrmRGV10f8wEFwpERvH4_
"""

user_input = input("กรุณากรอกอายุของคุณ (เป็นตัวเลขจำนวนเต็ม): ")

try:
    age = int(user_input)

    if age < 0:
        print("เนื่องจากไม่มีใครที่อายุจะติดลบได้ กรุณากรอกใหม่เพื่อความถูกต้องในการดำเนินการขั้นตอนถัดไป")

    elif age < 5:
        print("คำแนะนำ : คุณยังเด็กเกินไปสำหรับดูภาพยนตร์ ไปสนุกกับคาร์ตูนก่อนนะ")

    elif 5 <= age <= 12:
        print("คำแนะนำ : ควรชมภาพยนตร์เรต G หรือ PG")

    elif 13 <= age <= 17:
        print("คำแนะนำ : ควรชมภาพยนตร์เรต PG-13 หรือ R แต่ต้องมีผู้ปกครองให้คำแนะนำ")

    else:
        print("คำแนะนำ : คุณโตพอที่จะชมภาพยนตร์ได้ทุกเรตติ้ง")

        action_preference = input("คำถามเพิ่มเติม : คุณชอบภาพยนตร์แอคชันไหม? กรุณาตอบเป็น yes/no ): ").lower()
        if action_preference == "yes":
            print("คำแนะนำเพิ่มเติม : ดูเหมือนคุณอาจจะชอบภาพยนตร์แอคชันฟอร์มยักษ์เรื่องล่าสุดนะ ลองดูดูสิ ")

except ValueError:
    print("ไม่สามารถประมวลผลได้ กรุณากรอกอายุเป็นตัวเลขจำนวนเต็มเท่านั้น ")