# -*- coding: utf-8 -*-
"""lab2_1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJP-pmsOtw7LQztO4xc4F4ETSR5iQR0e
"""

user_input = input("กรุณากรอกตัวเลขจำนวนเต็ม 1 ตัว: ")
try:

    number = int(user_input)

    if number > 0:
        classification = "จำนวนบวก"
    elif number < 0:
        classification = "จำนวนลบ"
    else:
        classification = "ศูนย์"

    if number % 2 == 0:
        parity = "เลขคู่"
    else:
        parity = "เลขคี่"

    print(f"[ผลลัพธ์] {number} คือ {classification} และเป็น {parity}")

    if number > 0 and number % 2 == 0:
        print(f"Challenge: ตัวเลข {number} เป็นจำนวนบวกและเป็นเลขคู่")
    elif number > 0 and number % 2 != 0:
        print(f"Challenge: ตัวเลข {number} เป็นจำนวนบวกและเป็นเลขคี่")
    elif number < 0 and number % 2 == 0:
        print(f"Challenge: ตัวเลข {number} เป็นจำนวนลบและเป็นเลขคู่")
    elif number < 0 and number % 2 != 0:
        print(f"Challenge: ตัวเลข {number} เป็นจำนวนลบและเป็นเลขคี่")
    else:
        print(f"Challenge: ตัวเลขนี้คือ ศูนย์ ")

except ValueError:
    print("ไม่สามารถประมวลผลได้เนื่องจากค่าที่คุณกรอกไม่ได้เป็น 'ตัวเลขจำนวนเต็ม'")
    print("และเนื่องจากโปรแกรมนี้ถูกออกแบบมาเพื่อจำแนกจำนวนเต็มเท่านั้น จึงไม่รองรับเลขทศนิยมหรือตัวอักษรครับ :D")